language: cpp
env:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="master"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="master"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0.2"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0.2"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="2.8.12"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="2.8.12"
before_install:
  - git submodule update --init --recursive
  - sudo apt-get -y purge cmake
  - sudo add-apt-repository -y ppa:smspillaz/cmake-${CMAKE_VERSION}
  - sudo apt-add-repository -y ppa:saiarcot895/chromium-dev
  - gem install coveralls-lcov mdl
  - sudo pip install cmakelint polysquare-generic-file-linter polysquare-cmake-linter
  - sudo apt-get update -qq
  - sudo apt-get install `cat DEPENDENCIES`
  - cmake --version
script:
  - mkdir -p tests/build
  - pushd tests/build
  - cmake .. -Wdev --warn-uninitialized -G "${CMAKE_GENERATOR}" -DCMAKE_UNIT_LOG_COVERAGE=1 -DCMAKE_UNIT_COVERAGE_FILE=coverage.trace
  - ctest --output-on-failure
  - popd
  # Find all errors except:
  # 1. Spaces between control and condition (preferred style)
  # 2. Indentation errors
  - find . -type f -name "*.cmake" -not -path "./tests/build/*"| xargs cmakelint --spaces=4 --filter=-whitespace/extra,-whitespace/indent > .cmake-lint-log
  - cat .cmake-lint-log
  # Fails if file has length
  - echo "! [ -s .cmake-lint-log ]" > .check-link-script.bash
  - bash .check-link-script.bash
  # Lint markdown files
  - mdl .
  # Lint files for polysquare style guide
  - find . -type f -name "*.cmake" -not -path "./tests/build/*" -not -name "*FileForCoverage.cmake" | xargs polysquare-generic-file-linter
  - find . -type f -name "CMakeLists.txt" -not -path "./tests/build/*" | xargs polysquare-generic-file-linter
  # Lint files for polysquare cmake style guide.
  # access/other_private is disabled on .cmake files as the tests use private functions for now.
  - find . -type f -name "*.cmake" -not -path "./tests/build/*" -not -name "*FileForCoverage.cmake" | xargs polysquare-cmake-linter --blacklist access/other_private --namespace cmake_unit --indent 4
  - find . -type f -name "CMakeLists.txt" -not -path "./tests/build/*" | xargs polysquare-cmake-linter --blacklist access/other_private --namespace cmake_unit --indent 4
after_success:
  - cmake -DTRACEFILE=tests/build/coverage.trace -DLCOV_OUTPUT=tests/build/coverage.info -P CMakeTraceToLCov.cmake
  - coveralls-lcov tests/build/coverage.info
  - popd
