language: cpp
sudo: false
cache:
- ~/container
env:
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="master"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="master"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0.2"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0.2"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="2.8.12"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="2.8.12"
before_install:
# Setup python so that we can install packages on pip.
- wget public-travis-scripts.polysquare.org/setup-lang.sh
- source setup-lang.sh -l python -p ~/container/python
- export NAMESPACE="cmake_unit"
- export EXCLUDE_FROM_LINT="tests/FileForCoverage.cmake"
script:
- curl -LSs public-travis-scripts.polysquare.org/cmake-test-in-container.sh | bash
after_success:
- curl -LSs public-travis-scripts.polysquare.org/cmake-coverage.sh | bash
