language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: IH1xxQKcZW/0wW/G7kT9gGvLXvp38mX5mRrB0L2+AXNMO13/tejfnk/5IESMfqcBmj0cM5+8mm5Wg2eLoYWRXUA2bGFLIBABmCH0Nf1pZHacSTd7OtKgJkvYn+M5gZRdcWjsoo24kw4CWR2q+vUozmJTvKU/X0h35s9Bmvbwmtg=
  - secure: WOAONoUJfBh3TR2bylKn0OcqR2ZSPZ3vpSV48CeVTRx33buQTSjETsoNIgK1Nby/cl+27ltsNRq2zjbMs/To3Ny5Xj7hx+tSDfb7znCIH/s4PIdv6A8DlwNX284HGcQ/wrcIUuWmlX0qh9IsycDdWcVUQ21lqPfgjhUR+DD6VTY=
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace cmake_unit --generator
  "${CMAKE_GENERATOR}" --lint-exclude "*FileForCoverage.cmake"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package="smspillaz/cmake-unit"
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/cmake-unit
    branch: master
    condition: "${DEPLOY} = 1"
